# Generated by Django 3.1.2 on 2020-10-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_userlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
